import mongoose from "mongoose";

const CouponSchema = new mongoose.Schema({
  couponCode: {
    type: String,
    required: true,
  },
  discount: {
    type: String,
    required: true,
  },
  expiryDate: {
    type: Date,
    required: true,
  },
  userId: { 
    type: mongoose.Schema.Types.ObjectId, 
    ref: 'User', 
    default: null,
  },
  autoGenerated: { 
    type: Boolean, 
    default: false,
  },
});

const Coupon = mongoose.model("Coupon", CouponSchema);

export default Coupon;